### ISSUE TITLE
EXCEPTION_ILLEGAL_INSTRUCTION during HMC inversion in runHMCscript.jl

### ISSUE THREAD

**Issue by EkaAkbarPermatasari** [CUG-EMI/HMCMT2D#2]
I encountered an error while running the **runHMCscript.jl** script in the coprod2 example. The process fails during the HMC inversion step with an EXCEPTION_ILLEGAL_INSTRUCTION. 

**Steps to Reproduce**

1. Navigate to the coprod2 directory:

cd c:\Users\ASUS\Documents\GitHub\HMCMT2D\HMCMT\examples\coprod2

2. Execute the script:
julia "c:\Users\ASUS\Documents\GitHub\HMCMT2D\HMCMT\examples\coprod2\runHMCscript.jl"

3. Output
[Running] julia "c:\Users\ASUS\Documents\GitHub\HMCMT2D\HMCMT\examples\coprod2\runHMCscript.jl"
Reading datafile and modelfile ...
Current directory: c:\Users\ASUS\Documents\GitHub\HMCMT2D\HMCMT\examples\coprod2
Reading data file coprod2data.dat ...
  0.030197 seconds (1.58 k allocations: 201.789 KiB, 66.05% compilation time)
Reading model file coprod2.mod ...
  0.084248 seconds (33.96 k allocations: 2.404 MiB, 88.02% compilation time)
  0.162384 seconds (3.54 k allocations: 2.676 MiB, 98.32% compilation time)
setup inverse data and model ...
Performing HMC inversion ...

Invalid instruction at 00007ffd53ad74c0: 0xc5, 0xfa, 0x6f, 0x05, 0x40, 0x99, 0x09, 0x00, 0xb9, 0x02, 0x00, 0x00, 0x00, 0x4c, 0x8d

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x7ffd53ad74c0 -- blas_thread_server at c:\Users\ASUS\Documents\GitHub\HMCMT2D\MUMPS\lib\MUMPS.DLL (unknown line)
in expression starting at c:\Users\ASUS\Documents\GitHub\HMCMT2D\HMCMT\examples\coprod2\runHMCscript.jl:30
Allocations: 29726480 (Pool: 29679297; Big: 47183); GC: 40

**Environment**
Operating System: [Windows 10]
Julia Version: [1.10.4]
MUMPS Version: [I don't know]
CPU Architecture: [x86_64]
Logical Processor: 2 (Intel Celeron)

**Additional Information**
I have set the environment variables:

ENV["OMP_NUM_THREADS"] = 4
ENV["MKL_NUM_THREADS"] = 4
I also tried reducing the number of threads but the issue persists.

**Comment by liaoweiyang2017** [comment]
Whether you have downloaded the whole HMCMT2D code, and in this package we provide a MUMPS package, and then you change the directory to the `examples\coprod2\` folder, then input the following command:
```shell
julia runHMCscript.jl
```
And it can works fine. Here we setting the path properly. If you have installed the MUMPS package from offical package management environment, please delete it first.

**Comment by EkaAkbarPermatasari** [comment]
thank you for your response, sir
